BASE_TASK_CONFIG_PATH: habitat_extensions/config/rxr_vlnce_english_task.yaml
TRAINER_NAME: self_orientation_evaluator
SIMULATOR_GPU_IDS: [0]
TORCH_GPU_ID: 0
NUM_ENVIRONMENTS: 1
TENSORBOARD_DIR: data/tensorboard_dirs/rxr_so_cma_en
CHECKPOINT_FOLDER: data/checkpoints/rxr_so_cma_en
EVAL_CKPT_PATH_DIR: data/checkpoints/rxr_so_cma_en
RESULTS_DIR: data/checkpoints/rxr_so_cma_en/evals
# VIDEO_OPTION: ["disk"]
VIDEO_DIR: data/videos/rxr_so_cma_en
ENV_NAME: VLNCESelfOrientEnv

INFERENCE:
  SPLIT: test_challenge
  LANGUAGES: [en-US, en-IN]
  SAMPLE: True
  USE_CKPT_CONFIG: False
  CKPT_PATH: data/checkpoints/rxr_cma_en/RxR-en-CMA.pth
  PREDICTIONS_FILE: rxr_so_cma_en_test_challenge.jsonl
  FORMAT: rxr

EVAL:
  USE_CKPT_CONFIG: False
  SPLIT: val_unseen
  LANGUAGES: [en-US, en-IN]
  # EPISODE_COUNT: -1
  EPISODE_COUNT: 5
  SAMPLE: True

RL:
  POLICY:
    OBS_TRANSFORMS:
      ENABLED_TRANSFORMS: [ResizeShortestEdge, CenterCropperPerSensor]

IL:
  batch_size: 1
  epochs: 15
  inflection_weight_coef: 1.9

  SELF_ORIENTATION:
    entropy_threshold: 6.0
    entropy_history: 10
    budget_per_episode: 1

  RECOLLECT_TRAINER:
    preload_size: 30
    preload_trajectories_file: False
    trajectories_file: data/trajectories_dirs/rxr_en_guide_trim250/trajectories.json.gz
    max_traj_len: 250  # 1.3% of episodes in the English training split are above 250

MODEL:
  policy_name: CMAPolicy
  INSTRUCTION_ENCODER:
    bidirectional: True
    sensor_uuid: rxr_instruction
    embedding_size: 768
